// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/livingsyria-options/EditorialSouk.tsx": () => import("../components/mockups/livingsyria-options/EditorialSouk.tsx"),
  "./components/mockups/livingsyria-options/VibrantBazaar.tsx": () => import("../components/mockups/livingsyria-options/VibrantBazaar.tsx")
};
